apiVersion: v1
kind: Pod
metadata:
  name: martian-packets
  labels:
    run: martian-packets
  name: martian-packets
spec:
  containers:
  - image: rhysemmas/martian-packets:1.1
    imagePullPolicy: Always
    name: attacker
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    securityContext:
      capabilities:
        add: ["NET_RAW"]
    stdin: true
    tty: true
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/role: "master"
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
